### ISSUE TITLE
使用时，HproseHttpClient  时，服务器无返回数据 ，界面就全部卡主

### ISSUE THREAD

**Issue by 931743010** [hprose/hprose-objc#11]
+ (HproseClient*) sharedHPClient{
    static HproseClient *_sharedHPClient = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSString* webHost = API_HOST;
        _sharedHPClient = [[HproseHttpClient alloc] init:webHost];
        [_sharedHPClient setDelegate:self];
        [_sharedHPClient setOnError:@selector(errorHandler:withException:)];
        [_sharedHPClient setFilter:[LogFilter new]];
    });
    return _sharedHPClient;
}    

    [[HttpClient sharedHPClient] invoke:GetStatistics withArgs:@[text] block:^(id responseString, NSArray * params) {

**Comment by 931743010** [comment]
@干干净净#哈哈哈哈*``![]([[[]()]()]())

**Comment by andot** [comment]
你没写异常回调，所以如果发生错误，错误会忽略，你加上异常回调，就知道出错出在哪儿了。

**Comment by 931743010** [comment]
嗯，我换最新的库，是好的。应该是之前的库的问题。        是有异常回调的，但是没走进去，服务器是没有回应的。


在2016年03月31日 19:49，小马哥 写道:

你没写异常回调，所以如果发生错误，错误会忽略，你加上异常回调，就知道出错出在哪儿了。

**Comment by andot** [comment]
哦，对。原来的版本是有点问题
