### ISSUE TITLE
使用hprose-objc，为什么 每次 都会有2次网络请求 ；

### ISSUE THREAD

**Issue by 931743010** [hprose/hprose-objc#12]
用法 是参照demo
里面 写的

**Comment by andot** [comment]
每个调用一次请求，不知道你说的2次请求是指什么。

**Comment by 931743010** [comment]
[sharedHPClient invoke:@"getMoney" withArgs:@[text] block:^(id responseString, NSArray * params) {
最新的 这个 方法 丢弃了吗   换成最新的；没发现 这个方法

**Comment by andot** [comment]
嗯，master里面的是 2.0 版本（还未完成）。调用的API简化了，args 后面的选项参数合并为一个：settings 了，可以直接用 NSDictionary 来表示，例如：

```objective-c
    [client invoke:@"hello" withArgs:@[[text text]] settings:@{@"block":^(id result, NSArray * args) {
        [label setText:(NSString *)result];
    }, @"errorBlock":^(NSString *name, NSException *e) {
        [label setText:name];
    }}];
```
