### ISSUE TITLE
如何使用postman模拟发送请求

### ISSUE THREAD

**Issue by 931743010** [hprose/hprose-objc#13]
如何使用postman模拟hprose-oc客户端 向  hprose php的服务端 发送请求；尝试多次  失败；求解
1.设置了 服务器地址
2.设置了post参数

点击send
提示  系统发生错误

**Comment by andot** [comment]
hprose 的参数不是普通的 POST Form 格式。你要测试可以用：
http://hprose.com/test
来测试。

**Comment by 931743010** [comment]
格式也是可以自定义的 我使用PostMan  不知道如何设置 能给一个 postman的demo吗？http://hprose.com/test  一直提示 “ the hprose server erroe!!”

**Comment by andot** [comment]
使用 http://hprose.com/test 测试时，需要服务器端开启跨域选项，另外，注意 URL 路径是否正确，比如路径最后的 / 有时候不加也是不行的。

**Comment by andot** [comment]
![image](https://cloud.githubusercontent.com/assets/232161/16187748/8df9aea6-3704-11e6-9328-ce6561887176.png)
使用 postman 的话，提交要写 hprose 的序列化之后的请求数据，就比较麻烦了，上面是一个例子。
