### ISSUE TITLE
UIKIT_EXTERN not defined in Swift-based project for iOS

### ISSUE THREAD

**Issue by zhangchn** [hprose/hprose-objc#15]
In `Promise.h`, the macro `PROMISE_QUEUE` is dependent on definition (or the lack of) macro `UIKIT_EXTERN`. In a Swift based project built with recent SDKs, `UIKIT_EXTERN` is not imported from ObjC headers, leading to potential race conditions upon promise fulfillment and non-main-thread call to UI API issues.

**Comment by andot** [comment]
How can I fix it?

**Comment by andot** [comment]
I used UIKIT_EXTERN to distinguish between GUI or CLI.
