### ISSUE TITLE
关于promise then的回调

### ISSUE THREAD

**Issue by JohnWilley** [hprose/hprose-objc#16]
请问获取token后一直不走里面的回调是什么原因
- (Promise *) then:(id (^)(id))onfulfill catch:(id (^)(id))onreject {
    Promise * next = [Promise promise];
    @synchronized(_subscribers) {
        if (_state == FULFILLED) {
            promise_resolve(next, onfulfill, _result);
        }
        else if (_state == REJECTED) {
            promise_reject(next, onreject, _reason);
        }
        else {
            [_subscribers addObject:[Subscriber subscriber:next success:onfulfill fail:onreject]];
        }
    }
    return next;
}

在登陆成功后一直走_subscribers addObject:方法，请问这个应该怎么解决呢

**Comment by andot** [comment]
then 在执行的时候，如果结果已存在，才会走 promise_resolve，如果异常已存在，则会走 promise_reject，如果结果还未确定，就会走_subscribers addObject:，执行远程调用，是一个异步的相对耗时的操作，所以如果你在发起请求之后，接着执行then，那肯定结果是还未确定的，所以会将回调暂存起来，等结果到来之后再执行。这是一个正常的过程。
