### ISSUE TITLE
关于hprose中的service类问题

### ISSUE THREAD

**Issue by JohnWilley** [hprose/hprose-objc#17]
我看到Java中有一个类是HproseService 但是我看iOS的框架里面只有HproseClient 请问一下iOS这个框架可以做服务端吗？

**Comment by andot** [comment]
这个iOS版本只有客户端，没有服务端。

**Comment by JohnWilley** [comment]
问一下博主iOS后续版本会做服务端的吗

**Comment by andot** [comment]
iOS 平台本身没有提供实现一个 HTTP 服务器的 API，而且 iOS 平台也不支持后台运行程序，所以在 iOS 上实现一个服务器非常困难，而且似乎也没什么用处。
